---
title: "markdown_1"
author: "Phyliss"
date: "2017/7/3"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Download sleep study data
```{r}
library(readr)
sleep = read.csv("https://vincentarelbundock.github.io/Rdatasets/csv/lme4/sleepstudy.csv")
head(sleep)
```

Plot the data by subject
```{r}
library(ggplot2)
ggplot(sleep, aes(x = Days, y = Reaction)) +
  geom_point() +
  geom_smooth() +
  scale_x_continuous(breaks = seq(0, 8, by = 2)) +
  facet_wrap(~ Subject)
```

Summary statistics by subject

```{r}
library(dplyr)
sleep %>%
  group_by(Subject) %>%
  summarise(mean(Reaction))
```


Mean-center reaction times and plot on a single axis

```{r}
sleep %>%
  group_by(Subject) %>%
  mutate(mean_centered_reaction = Reaction - mean(Reaction)) %>%
  ggplot(aes(x = Days, y = mean_centered_reaction,
      colour = factor(Subject))) + 
    geom_smooth(show.legend = FALSE, se = FALSE) +
    scale_x_continuous(breaks = seq(0, 8, by = 2))
```

Task 5 for plotting
```{r}
library(ggplot2)
ggplot(mpg,aes(x = displ, y = hwy,group = Cyclinders))+geom_point(aes(color = Cyclinders))+geom_smooth(method = 'lm',se = FALSE, aes(color = Cyclinders))+facet_wrap(~year)+labs(x='Displacement',y="MPG highway",title = 'Fuel economy and engine size')
```

task 6-11 for data manipulation
```{r}
library(tidyverse)
data(mpg, package = "ggplot2")
mpg2 = mpg %>% select(manufacturer, model, displ, year, cyl, trans, cty, hwy)
mpg2 %>% mutate(displ2 = displ^2) 
mpg2 %>% mutate(vol_per_cyl = round(displ / cyl,2))

mpg3 = mpg2 %>%
            mutate(displ2 = displ^2) %>%
            mutate(vol_per_cyl = round(displ / cyl,2))
mpg3 %>% arrange(desc(vol_per_cyl))
mpg3 %>% filter(manufacturer == 'chevrolet') %>% arrange(desc(vol_per_cyl))
mpg4 = mpg3 %>% group_by(manufacturer,year) %>% summarise(max_vol_per_cyl = max(vol_per_cyl))

library(tidyr)
mpg5 = mpg4 %>% spread(year,max_vol_per_cyl)
mpg6 = mpg5 %>% mutate(change = `2008` - `1999`)
mpg6 %>% rename(max_vpc_1999 = `1999`, max_vpc_2008 = `2008` ) %>% gather(variable, value, max_vpc_1999, max_vpc_2008) %>% select(-change) %>% View
```

task 12-14 for data merging
```{r}
library(tidyverse)
library(nycflights13)
flights2 = flights %>% select(origin, year, month, day, hour, 
    sched_dep_time, dep_delay, carrier)
weather2 = weather %>% select(origin, year, month, day, hour, 
    precip, wind_speed, visib)

inner_join(flights, airlines)

flights2 %>% full_join(weather2)

weather2 %>% summarise(min_precip = min(precip, na.rm = TRUE), 
    min_wind = min(wind_speed, na.rm = TRUE), max_visib = max(visib, 
        na.rm = TRUE))

good_weather_delays =  inner_join(flights2, weather2) %>% filter(precip == 0, wind_speed == 0, visib == 10)

avg_good_weather_delays = good_weather_delays %>% group_by(carrier) %>% summarise(dep_delay = mean(dep_delay,na.rm = TRUE)) %>% arrange(desc(dep_delay)) %>% left_join(airlines)

ranked_airline_labels <- avg_good_weather_delays %>% transmute(carrier, name = factor(-row_number(), labels = name))

good_weather_delays %>% inner_join(ranked_airline_labels) %>% ggplot(aes(x = name, y = dep_delay)) + stat_summary() + coord_flip() + labs(x = "", y = "Average departure delay", title = "Departure delays under ideal weather conditions\nNYC airports, 2013")
```

